---
#========================================================================
# Copyright Universidade Federal do Espirito Santo (Ufes)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 
# This program is released under license GNU GPL v3+ license.
#
#========================================================================

version: '3.8'

services:

    # web app
    boca-web:
        env_file: .env
        environment:
            # database configuration
            # privileged user password
            - BOCA_DB_SUPER_PASSWORD=${PASSWORD_DB}
        ports: 
            - ${PORT_BOCA}:80
        networks:
            - boca
        
    # database
    boca-db:
        image: postgres:14-alpine
        env_file: .env
        environment:
            # database configuration
            # privileged user password
            - POSTGRES_PASSWORD=${PASSWORD_DB}
        ports: 
            - ${PORT_DB}:5432
        networks:
            - boca

networks:
  boca:
    driver: bridge